#include <CASE_Filter_OR_thr_Impl_adapter.h>

Unit hamr_SW_CASE_Filter_OR_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_FLT_OR_CASE_Filter_OR_CASE_Filter_OR_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_CASE_Filter_OR_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_FLT_OR_CASE_Filter_OR_CASE_Filter_OR_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_CASE_Filter_OR_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_FLT_OR_CASE_Filter_OR_CASE_Filter_OR_computeEntryPoint(SF_LAST);
}
