#include <CASE_AttestationManager_thr_Impl_adapter.h>

Unit hamr_SW_CASE_AttestationManager_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_AM_CASE_AttestationManager_CASE_AttestationManager_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_CASE_AttestationManager_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_AM_CASE_AttestationManager_CASE_AttestationManager_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_CASE_AttestationManager_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_AM_CASE_AttestationManager_CASE_AttestationManager_computeEntryPoint(SF_LAST);
}
