#ifndef UARTDRIVER_IMPL_ADAPTER_H
#define UARTDRIVER_IMPL_ADAPTER_H

#include <all.h>

Unit hamr_Drivers_UARTDriver_Impl_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit hamr_Drivers_UARTDriver_Impl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit hamr_Drivers_UARTDriver_Impl_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints hamr_Drivers_UARTDriver_Impl_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
